AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Cluster'
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: cloud-devops-app

Resources:
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Sub '${EnvironmentName}-cluster'
      Version: '1.15'
      RoleArn:
        Fn::ImportValue: !Sub '${EnvironmentName}-CLUSTER-ROLE'
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub '${EnvironmentName}-SECURITY-GROUPS'
        SubnetIds: !Split
          - ','
          - Fn::ImportValue: !Sub '${EnvironmentName}-SUB-NETS'
