AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Node Group'
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: cloud-devops-app
  WorkerNodeInstance:
    Description: Worker node image instance
    Type: String
    Default: t2.micro

Resources:
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Sub '${EnvironmentName}-cluster'
      NodeRole:
        Fn::ImportValue: !Sub '${EnvironmentName}-NODEGROUP-ROLE'
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      InstanceTypes:
        - !Ref WorkerNodeInstance
      Subnets: !Split
        - ','
        - Fn::ImportValue: !Sub '${EnvironmentName}-PRIVATE-SUB-NETS'
