apiVersion: v1
kind: Service
metadata:
  name: cloud-devops-app
spec:
  type: LoadBalancer
  selector:
    app: cloud-devops-app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-app-deploy
spec:
  selector:
    matchLabels:
      app: cloud-devops-app
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud-devops-app
    spec:
      containers:
        - name: cloud-devops-app-pod
          image: pembeweb/cloud-devops-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
  strategy:
    type: RollingUpdate
